### PR TITLE
fix resource name for neptune db subnet group

### PR DESCRIPTION
**Pull request by shooit**

### CODE REVIEW

**Review by keerts — APPROVED** [review]

**Comment by shooit** [comment]
@keerts @brabster I was trying to release this but wasn't sure of the steps. Do I need to manually add the `.zip` and `.tar.gz` files or do those get added automatically? How does the release go out to maven?

**Comment by keerts** [comment]
We use Github releases for that. Follow steps 1 to 6 from https://help.github.com/en/articles/creating-releases.

**Comment by keerts** [comment]
Do you want to try? I will be around a few minutes to answer questions.

**Comment by shooit** [comment]
Thanks. Yes, trying now.

**Comment by shooit** [comment]
Easy... and github pushes the artifacts out?

**Comment by keerts** [comment]
What happens after is magic for me, it's @brabster magic. It all just happens.

**Comment by shooit** [comment]
🙏 🔮 🙏

**Comment by keerts** [comment]
That's basically my thoughts every time this just works. Thanks @brabster, at some point in time, before it breaks down, you will have to teach us.

**Comment by keerts** [comment]
I'm guessing it's not all that hard, but I never got into it.

**Pull request merged**
