### PR TITLE
Feature/ecs support

### PR DESCRIPTION
**Pull request by keerts**
Planning to add loadbalancingv2 to this and subnetting, so there is more to come. Treat this pr as a preview. In the meantime, any comment is welcome.

### CODE REVIEW

**Comment by brabster** [comment]
:+1:

**Comment by brabster** [comment]
Hi @keerts, is this your long-running PR or are you looking to get it merged now?

**Comment by keerts** [comment]
This is still work in progress, I'm just pushing now and then, to let you know there is progress. It's good stuff, but needs more testing.

**Comment by brabster** [comment]
Just letting you know - I've made a couple of releases over the last week, nothing major just dependency updates etc. Hopefully won't cause any issues when you merge.

**Comment by keerts** [comment]
Please don't wait for me. If I run into problems merging I'll figure it out. Next week is going to have more time. We moved into a new office and tomorrow is the opening. If you happen to be in the Netherlands ;-)
image

**Comment by brabster** [comment]
Nice!

**Comment by keerts** [comment]
Split out the IAM and EC2 parts into separate pull requests. More to follow!

**Comment by keerts** [comment]
Feel free to deny / close this pr.

**Pull request closed without merging**
